# test
version: "3"
services:
  fluentd1:
    container_name: 'fluentd1'
    image: fluentd:2022.08
    volumes:
      - .:/fluentd/etc
      - /Users/hwangsero/log/fluentd:/fluentd/log
    working_dir: /fluentd/etc
    ports:
      - 9880:9880
    command:
      -c /fluentd/etc/fluentd1.conf
    privileged: true

  fluentd2:
    container_name: 'fluentd2'
    image: fluentd:2022.08
    volumes:
      - .:/fluentd/etc
      - /Users/hwangsero/log/fluentd:/fluentd/log
    working_dir: /fluentd/etc
    ports:
      - 24224:24224
    command:
      -c /fluentd/etc/fluentd2.conf
    privileged: true
       
networks:
  default:
    external:
      name: hadoop_network
